### Basics Of Python

In [2]:
a= 5
b = 4
sum = a+b
sum

9

In [3]:
a = 5
A = 4
a + A

9

In [4]:
a = 45+65+78+79+34
a

301

In [5]:
a,b,c = 24,54,"hello"
print(a,b,c)

24 54 hello


In [6]:
x = 91
y = 24
x*y


2184

In [7]:
li = [1,2,3,4,'h', 5.4]
li

[1, 2, 3, 4, 'h', 5.4]

In [8]:
type(li)

list

In [9]:
li[2]

3

In [11]:
# Hyphen or any special character except _ cannot be used in variable                 
sample-list = [12,13]
sample-list

SyntaxError: cannot assign to operator (<ipython-input-11-e305dc83fe4d>, line 1)

In [12]:
li[2] = 1.2
li
# List is mutable

[1, 2, 1.2, 4, 'h', 5.4]

In [13]:
li.reverse()

In [14]:
li

[5.4, 'h', 4, 1.2, 2, 1]

In [15]:
tu = (2,3,4,5,'hi')
tu

(2, 3, 4, 5, 'hi')

In [16]:
tu[2] = 2.5

TypeError: 'tuple' object does not support item assignment

In [17]:
se = {1,43,23,45,67,22,21}
se

{1, 21, 22, 23, 43, 45, 67}

In [18]:
se[2]

TypeError: 'set' object is not subscriptable

In [19]:
se.add(90)
se

{1, 21, 22, 23, 43, 45, 67, 90}

In [20]:
se.remove(43)
se

{1, 21, 22, 23, 45, 67, 90}

In [21]:
se.pop()

1

In [22]:
di = {
    'a':"alpha",
    'b':"beta",
    'g':"gamma",
    'a':"first"
}
di

{'a': 'first', 'b': 'beta', 'g': 'gamma'}

### Numpy 

In [27]:
import numpy as np
simple_list = [1,2,3]
arr = np.array([1,2,3])
type(arr)

numpy.ndarray

In [28]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
a = np.arange(5,21)
a.reshape(4,4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [32]:
b = np.arange(5,71,5,dtype = float)
b

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65.,
       70.])

In [36]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [38]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

# Np Random

In [42]:
np.random.randn(5,4)
# standard normal distribution

array([[-0.36117367,  0.54676226, -0.4009214 , -0.60411764],
       [ 0.8630507 ,  0.45462414, -0.04715584, -1.07854495],
       [ 0.07161645, -0.09666043, -1.03600991,  0.4903802 ],
       [-3.03248043, -0.37703256, -0.83221127,  0.78900549],
       [-0.5934656 , -0.32788541,  1.67894773, -0.12982396]])

In [43]:
np.random.rand(2,3)
# 2X3 size and uniform random values

array([[0.73722714, 0.80911238, 0.40788544],
       [0.4352617 , 0.53236651, 0.74928871]])

In [44]:
np.random.randint(1,10)
# random integer excluding 10

7

In [45]:
np.random.randint(1,10,100)
# 100 numbers from 1 to 10 excluding 10

array([6, 1, 5, 5, 9, 5, 8, 6, 4, 6, 8, 9, 3, 2, 5, 6, 3, 9, 4, 7, 7, 9,
       5, 4, 6, 9, 4, 8, 8, 3, 4, 3, 8, 9, 6, 8, 8, 9, 4, 1, 7, 1, 3, 6,
       5, 9, 4, 3, 1, 5, 2, 1, 6, 6, 7, 5, 8, 8, 2, 3, 1, 6, 4, 5, 2, 8,
       2, 7, 8, 8, 5, 5, 6, 1, 6, 7, 6, 5, 6, 9, 2, 9, 5, 5, 4, 6, 1, 8,
       9, 4, 6, 5, 5, 2, 1, 2, 6, 4, 2, 5])

In [47]:
np.random.randint(1,10,100)

array([9, 9, 2, 9, 9, 7, 5, 5, 2, 4, 9, 2, 7, 1, 6, 7, 5, 7, 8, 1, 9, 1,
       3, 5, 5, 9, 6, 5, 1, 8, 6, 9, 2, 7, 7, 8, 7, 4, 5, 1, 7, 5, 9, 2,
       9, 4, 5, 2, 3, 7, 3, 7, 2, 8, 1, 8, 9, 3, 2, 5, 6, 9, 6, 6, 8, 2,
       3, 9, 4, 5, 5, 2, 6, 2, 4, 6, 2, 5, 8, 1, 9, 3, 2, 3, 7, 6, 1, 3,
       4, 8, 6, 6, 9, 1, 7, 2, 7, 1, 9, 3])

In [48]:
rand_array = np.random.randint(0,100,20)
rand_array.reshape(5,4)

array([[71, 22,  0, 74],
       [ 9, 75, 84, 77],
       [69, 59, 88, 14],
       [44, 79, 15, 67],
       [52, 82, 43, 14]])

In [49]:
rand_array.max()

88

In [50]:
rand_array.min()

0

In [51]:
rand_array.argmax()
# linear index of max element

10

In [52]:
rand_array.argmin()
# linear index of min element

2

In [53]:
rand_array.T

array([71, 22,  0, 74,  9, 75, 84, 77, 69, 59, 88, 14, 44, 79, 15, 67, 52,
       82, 43, 14])

In [55]:
rand_array.dtype

dtype('int32')

In [57]:
rand_array.shape

(20,)

In [61]:
sample_array = np.array(([1,2,3], [4,5,6], [7,8,9]))
sample_array
sample_array[1:2,1:2]

array([[5]])

# Pandas

# Statistics

In [3]:
import numpy as np
d1 = np.array([1,2,3,4,5])
d2 = np.array([20,40,60,80,100])
d3 = np.array([1,2,3,4,5,200])
d4 = np.array([21,16,42,29])
print(np.mean(d1))
print(np.mean(d2))
print(np.mean(d3))
print(np.mean(d4))

3.0
60.0
35.833333333333336
27.0


In [4]:
print(np.median(d1))
print(np.median(d2))
print(np.median(d3))
print(np.median(d4))

3.0
60.0
3.5
25.0


In [6]:
# import statistics as stats will give only 2
from scipy import stats
print(stats.mode([4,2,4,3,2,2]))

ModeResult(mode=array([2]), count=array([3]))


In [7]:
print(np.var(d1))

2.0


In [9]:
d5 = np.array([1,11,121,24,16])
print(np.var(d5))

1921.8400000000001


In [12]:
print(np.std(d1))

1.4142135623730951


In [13]:
from statistics import variance
print(variance(d1))

2
